
version: 2
updates:
- package-ecosystem: nuget
  directory: "/Cake.Frosting.Issues.Recipe"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Cake.Frosting
    versions:
    - "> 1.0.0, < 2"